services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service_container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/users

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task_service_container
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasks

volumes:
  mongo_data: